version: 2

jobs:
  linux-wheels:
    working_directory: ~/linux-wheels
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the Linux wheels.
          command: |
            pip install --user cibuildwheel
            ~/.local/bin/cibuildwheel --output-dir wheelhouse
      - store_artifacts:
          path: wheelhouse/


workflows:
  version: 2
  all-tests:
    jobs:
      - linux-wheels